name = "clojure"
entrypoint = "main.clj"
extensions = [
  "clj",
  "cljc",
  "cljs",
  "edn"
]
packages = [
  "openjdk-11-jre-headless"
]
setup = [
  "wget https://download.clojure.org/install/linux-install-1.10.1.536.sh",
  "chmod +x linux-install-1.10.1.536.sh",
  "./linux-install-1.10.1.536.sh",
  "rm linux-install-1.10.1.536.sh",

  # Fetch Maven artifacts eagerly in order to cache them in the container image.
  # (https://clojure.org/reference/deps_and_cli#_command_line_tools)
  """clojure -Sverbose \
             -Sdeps '{:deps {org.clojure/tools.namespace {:mvn/version \"1.0.0\"}} :mvn/local-repo \"/home/runner/.m2/repository\"}' \
             --eval ''""",

  "/usr/bin/build-prybar-lang.sh clojure"
]
versionCommand = [
  "clojure",
  "--eval",
  "(clojure-version)"
]

[run]
command = [
  "clojure",
  "main.clj"
]

[tests]

  [tests.hello]
  code = "(println \"hello\")"
  output = "hello\n"
